<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QATableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('qa_db')->truncate();
        DB::table('qa_db')->insert([

            // Copy the below code to feed all questions in database.
            [
                'subject' => 'DSA',
                'question' => 'Queue data structure works on ?',
                'correct_option' => 'FIFO',
                'other_option1' => 'LIFO',
                'other_option2' => 'FILO',
                'other_option3' => 'None of the above',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
                ],
            [
                'subject' => 'DSA',
                'question' => 'What could be the worst case height of an AVL tree?',
                'correct_option' => '1.44 log n',
                'other_option1' => '0.97 log n',
                'other_option2' => '2.13 log n',
                'other_option3' => 'n2 log n',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'High',
                ],
            [
                'subject' => 'DSA',
                'question' => 'If locality is a concern, you can use _______ to traverse the graph?',
                'correct_option' => 'Depth First Search',
                'other_option1' => 'Breadth First Search',
                'other_option2' => 'Either BFS or DFS',
                'other_option3' => 'None of the above',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'DSA',
                'question' => 'Which of the following asymptotic notation is the worst among all?',
                'correct_option' => 'Ο(n3)',
                'other_option1' => 'Ο(n+9378)',
                'other_option2' => 'nΟ(1)',
                'other_option3' => ' 2Ο(n)',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'DSA',
                'question' => 'To represent hierarchical relationship between elements, Which data structure is suitable??',
                'correct_option' => 'Tree',
                'other_option1' => 'Priority',
                'other_option2' => 'Graph',
                'other_option3' => 'Dequeue',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'DSA',
                'question' => '…………… is not the component of data structure.?',
                'correct_option' => 'None of above',
                'other_option1' => 'Operations',
                'other_option2' => 'Storage Structures',
                'other_option3' => 'Algorithms',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'DSA',
                'question' => 'Which of the following is the most widely used external memory data structure?',
                'correct_option' => 'B-tree',
                'other_option1' => 'AVL tree',
                'other_option2' => 'Red-black tree',
                'other_option3' => 'Both AVL tree and Red-black tree',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'DSA',
                'question' => 'What is the disadvantages of implementing tree using normal arrays?',
                'correct_option' => 'have to know the maximum number of nodes possible before creation of trees',
                'other_option1' => 'difficulty in knowing children nodes of a node',
                'other_option2' => 'difficult in finding the parent of a node',
                'other_option3' => 'difficult to implement',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'DSA',
                'question' => 'Which of the following traversing algorithm is not used to traverse in a tree?',
                'correct_option' => 'Randomized',
                'other_option1' => 'Post order',
                'other_option2' => 'Pre order',
                'other_option3' => 'Both',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'DSA',
                'question' => 'What is the time complexity for converting decimal to binary numbers?',
                'correct_option' => 'O(logn)',
                'other_option1' => 'O(1)',
                'other_option2' => 'O(n)',
                'other_option3' => 'O(nlogn)',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'DSA',
                'question' => 'Heap can be used as ________________',
                'correct_option' => 'Priority queue',
                'other_option1' => 'Stack',
                'other_option2' => 'A decreasing order array',
                'other_option3' => 'Normal Array',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'DSA',
                'question' => 'What is the maximum number of edges in a bipartite graph having 10 vertices?',
                'correct_option' => '25',
                'other_option1' => '24',
                'other_option2' => '21',
                'other_option3' => '16',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'High',
            ],
            [
                'subject' => 'DSA',
                'question' => 'With what data structure can a priority queue be implemented?',
                'correct_option' => 'Tree',
                'other_option1' => 'Array',
                'other_option2' => 'List',
                'other_option3' => 'Heap',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'DSA',
                'question' => 'What is an AVL tree?',
                'correct_option' => 'a tree which is balanced and is a height balanced tree',
                'other_option1' => 'a tree which is unbalanced and is a height balanced tree',
                'other_option2' => 'a tree with three children',
                'other_option3' => 'a tree with atmost 3 children',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'DSA',
                'question' => 'What is the hash function used in the division method?',
                'correct_option' => 'h(k) = k mod m',
                'other_option1' => 'h(k) = k/m',
                'other_option2' => 'h(k) = m/k',
                'other_option3' => 'h(k) = m mod k',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'DSA',
                'question' => 'A procedure that calls itself is called',
                'correct_option' => 'recursive',
                'other_option1' => 'illegal call',
                'other_option2' => 'reverse polish',
                'other_option3' => 'none of the above',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'DSA',
                'question' => 'Which of the following is not possible with an array in C programming langauge?',
                'correct_option' => 'Dynamic Allocation',
                'other_option1' => 'Declaration',
                'other_option2' => 'Definition',
                'other_option3' => 'Array of strings',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'ML',
                'question' => 'Machine learning is',
                'correct_option' => 'The autonomous acquisition of knowledge through the use of computer programs',
                'other_option1' => 'The autonomous acquisition of knowledge through the use of manual programs',
                'other_option2' => 'The selective acquisition of knowledge through the use of computer programs',
                'other_option3' => 'The selective acquisition of knowledge through the use of manual programs',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'ML',
                'question' => 'Bayesian classifiers is',
                'correct_option' => 'A class of learning algorithm that tries to find an optimum classification of a set of examples using the probabilistic theory.',
                'other_option1' => 'Any mechanism employed by a learning system to constrain the search space of a hypothesis',
                'other_option2' => 'An approach to the design of learning algorithms that is inspired by the fact that when people encounter new situations, they often explain them by reference to familiar experiences, adapting the explanations to fit the new situation.',
                'other_option3' => 'None of these.',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'ML',
                'question' => 'Classification is',
                'correct_option' => 'A subdivision of a set of examples into a number of classes',
                'other_option1' => 'A measure of the accuracy, of the classification of a concept that is given by a certain theory',
                'other_option2' => 'The task of assigning a classification to a set of examples',
                'other_option3' => 'None of these',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'ML',
                'question' => 'How many types of agents are there in artificial intelligence',
                'correct_option' => '4',
                'other_option1' => '1',
                'other_option2' => '2',
                'other_option3' => '3',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'ML',
                'question' => 'Which of the following is a categorical outcome?',
                'correct_option' => 'Accuracy',
                'other_option1' => 'RMSE',
                'other_option2' => 'RSquared',
                'other_option3' => 'All of the Mentioned',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'ML',
                'question' => 'Which of the following is an example of feature extraction?',
                'correct_option' => 'All of the above',
                'other_option1' => 'Constructing bag of words vector from an email',
                'other_option2' => 'Applying PCA projects to a large high-dimensional data',
                'other_option3' => 'Removing stopwords in a sentence',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'ML',
                'question' => 'Which of the following techniques can be used for normalization in text mining?',
                'correct_option' => 'Both A and B',
                'other_option1' => 'Stemming',
                'other_option2' => 'Lemmatization',
                'other_option3' => 'Stop Word Removal',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'High',
            ],
            [
                'subject' => 'ML',
                'question' => 'To find the minimum or the maximum of a function, we set the gradient to zero because:',
                'correct_option' => 'The value of the gradient at extrema of a function is always zero',
                'other_option1' => 'Depends on the type of problem',
                'other_option2' => 'Both A and B',
                'other_option3' => 'None of the above',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'High',
            ],
            [
                'subject' => 'ML',
                'question' => 'Another name for an output attribute',
                'correct_option' => 'Independent variable',
                'other_option1' => 'predictive variable',
                'other_option2' => 'estimated variable',
                'other_option3' => 'Dependent variable',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'ML',
                'question' => 'Computational complexity of Gradient descent is',
                'correct_option' => 'Polynomial in D',
                'other_option1' => 'linear in D',
                'other_option2' => 'Linear in N',
                'other_option3' => 'Dependent on number of iterations',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'High',
            ],
            [
                'subject' => 'ML',
                'question' => 'Data used to build a data mining model',
                'correct_option' => 'Training data',
                'other_option1' => 'validation data',
                'other_option2' => 'Test data',
                'other_option3' => 'Hidden data',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'ML',
                'question' => 'K-fold cross-validation is',
                'correct_option' => 'linear in K',
                'other_option1' => 'quadratic in K',
                'other_option2' => 'Cubic in K',
                'other_option3' => 'Exponential in K',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'ML',
                'question' => 'Regression trees are often used to model _________ data',
                'correct_option' => 'Non-linear',
                'other_option1' => 'linear',
                'other_option2' => 'Categorical',
                'other_option3' => 'Symmetrical',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'Java',
                'question' => 'Method Overriding is an example of',
                'correct_option' => 'Dynamic Binding',
                'other_option1' => 'Static Binding.',
                'other_option2' => 'Both of the above',
                'other_option3' => 'None of the above',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'Java',
                'question' => 'Java Source Code is compiled into ______________',
                'correct_option' => 'Bytecode',
                'other_option1' => '.Obj',
                'other_option2' => 'Source Code',
                'other_option3' => '.Exe',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'Java',
                'question' => 'Which of the tool is used to compile java code ?',
                'correct_option' => 'javac',
                'other_option1' => 'javadoc',
                'other_option2' => 'jar',
                'other_option3' => 'java',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'Java',
                'question' => 'Which of the following tool used to execute java code.?',
                'correct_option' => 'java',
                'other_option1' => 'javac',
                'other_option2' => 'javadoc',
                'other_option3' => 'rmic',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'Java',
                'question' => 'Which of the following is used to interpret and execute Java Applet Classes hosted by HTML.',
                'correct_option' => 'appletviewer',
                'other_option1' => 'appletscreen',
                'other_option2' => 'appletwatcher',
                'other_option3' => 'appletshow',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'High',
            ],
            [
                'subject' => 'Java',
                'question' => 'HTML based Java Documentary help can be accessed using ______________.',
                'correct_option' => 'javadoc',
                'other_option1' => 'javamanual',
                'other_option2' => 'none of these',
                'other_option3' => 'javahelp',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'Java',
                'question' => 'jar stands for _____________.',
                'correct_option' => 'Java Archive',
                'other_option1' => 'Java Application Runner',
                'other_option2' => 'Java Archive Runner',
                'other_option3' => 'none of these',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'Java',
                'question' => 'Who is the father of Java?',
                'correct_option' => 'James Gosling',
                'other_option1' => 'Donald Knuth',
                'other_option2' => 'Dennis Ritchie',
                'other_option3' => 'Jim Gray',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'Java',
                'question' => 'To compile, debug and execute a program written in java, _______________ is required.',
                'correct_option' => 'JDK',
                'other_option1' => 'JVM',
                'other_option2' => 'JRE',
                'other_option3' => 'JIT',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'Java',
                'question' => 'What is Polymorphism?',
                'correct_option' => 'ability to have many forms',
                'other_option1' => 'hiding the properties',
                'other_option2' => 'ability to acquire the properties',
                'other_option3' => 'blueprint for an object',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'Java',
                'question' => 'Who executes the byte code in java?',
                'correct_option' => 'JVM',
                'other_option1' => 'OS',
                'other_option2' => 'JRE',
                'other_option3' => 'JDK',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'Java',
                'question' => '__________ generates the byte code for a given file with .java extension.',
                'correct_option' => 'JDK',
                'other_option1' => 'JRE',
                'other_option2' => 'JVM',
                'other_option3' => 'OS',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Basic',
            ],
            [
                'subject' => 'Java',
                'question' => 'Which edition of java is used for developing web application?',
                'correct_option' => 'J2EE',
                'other_option1' => 'J2ME',
                'other_option2' => 'J2SE',
                'other_option3' => 'All these options',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
            [
                'subject' => 'Java',
                'question' => 'Which edition of java is used for developing web application?',
                'correct_option' => 'J2EE',
                'other_option1' => 'J2ME',
                'other_option2' => 'J2SE',
                'other_option3' => 'All these options',
                'answer_explanation' => 'Input some sense here please',
                'answer_diagram' => 'Not available',
                'level' => 'Medium',
            ],
        ]);
    }
}
?>